version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    open-pull-requests-limit: 6
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      test-libs:
        patterns:
          - "junit:*"
          - "org.mockito:*"
          - "org.robolectric:*"
          - "org.hamcrest:*"
          - "io.mockk:*"
          - "com.google.truth:*"
      networking-and-firebase:
        patterns:
          - "com.squareup.okhttp3:*"
          - "com.squareup.retrofit2:*"
          - "com.google.firebase:*"
